### ISSUE TITLE
ensure grammar is aligned with string_serialization in yaml

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl#13]
The yaml has string serializations

```yaml
  node rename:
    is_a: node change
    description: >-
      A node change where the name (aka rdfs:label) of the node changes
    slots:
      - old value
      - new value
      - has textual diff      
      - new language
      - old language

    slot_usage:
      old value:
        multivalued: false
      new value:
        multivalued: false
      change description:
        string_serialization: "rename {about node} from {old value} to {new value}"
    examples:
      - value: "rename UBERON:0002398 from 'manus' to 'hand'"
        description: "replacing the rdfs:label of 'manus' on an uberon class with the rdfs:label 'hand'"
```

but these are not always aligned with the grammar
